
size:
  width: 1366 
  height: 600   
fps: 2          

theme: themes

fonts:
  default:
    font-family:  OpenSans-Regular
    font-size: 22
  intro-text:
    font-family:  OpenSans-Bold
    font-size: 60
watermark: on
intro-text:
  text: "Techno-Disaster"
  time: 3 